stages:
  - quality
  - testing
  - build
  - deploy

variables:
  HEROKU_RUNTIME: "python-3.8.2"

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - runtime.txt
    - requirements.txt

include:
  - local: .gitlab/ci/templates.gitlab-ci.yml
  - local: .gitlab/ci/quality.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/deploy.gitlab-ci.yml
