on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
      - requested

name: Continuous Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Export Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry export -f requirements.txt > requirements.txt

      - name: Export Heroku runtime
        run: echo "python-3.8.3" > runtime.txt

      - name: Deploy to Heroku
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - run: |
          gem install dpl
          dpl --provider=heroku --app=${{ secrets.HEROKU_STAGING_SERVER_APP_NAME }} --api-key=${{ secrets.HEROKU_STAGING_SERVER_KEY }} --skip-cleanup=true
