on:
  push:
    branches-ignore:
      - master
      - development
  pull_request:
    branches:
      - development
    paths:
      - ".github/workflows/**"
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"

name: Continuous Integration

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry install

      # Pydocstyle:
      #   - D101: Missing docstring in public class.
      #   - D102: Missing docstring in public method.
      #   - D103: Missing docstring in public function.
      - name: Quality
        run: |
          poetry run pylama server
          poetry run pydocstyle --select=D101,D102,D103 server
          poetry run black -l 79 --check server

      - name: Testing and code coverage
        run: |
          poetry run coverage run -m unittest discover -s test/unit -v
          poetry run coverage report
