name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HEROKU_RUNTIME: python-3.8.3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry --version
        poetry export -f requirements.txt > requirements.txt

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - run: |
          gem install dpl
