on:
  create:
    tags:
      - "*"

name: Deploy to production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.0.10"

      - name: setup project dependencies
        run: poetry install

      - name: run quality jobs
        run: ./scripts/quality.sh

      - name: unit tests and code coverage
        run: ./scripts/test.sh

      - name: upload code coverage
        uses: codecov/codecov-action@v1

      - name: export Heroku runtime
        run: echo "python-3.8.3" > runtime.txt

      - name: export Python dependencies
        run: poetry export -f requirements.txt > requirements.txt

      - name: setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: deploy to production
        run: |
          gem install dpl
          dpl --provider=heroku --app=${{ secrets.HEROKU_SERVER_APP_NAME }} --api-key=${{ secrets.HEROKU_SERVER_KEY }} --skip-cleanup=true
