on:
  push:
    branches:
      - development

    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .coveragerc

name: Deploy to staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.0.10"

      - name: setup project dependencies
        run: poetry install

      - name: run quality jobs
        run: ./scripts/quality.sh

      - name: unit tests and code coverage
        run: ./scripts/test.sh

      - name: export Heroku runtime
        run: echo "python-3.8.3" > runtime.txt

      - name: Export Python dependencies
        run: poetry export -f requirements.txt > requirements.txt

      - name: setup Ruby 2.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: deploy to staging
        run: |
          gem install dpl
          dpl --provider=heroku --app=${{ secrets.HEROKU_STAGING_SERVER_APP_NAME }} --api-key=${{ secrets.HEROKU_STAGING_SERVER_KEY }} --skip-cleanup=true
