deploy to heroku:

  stage: deploy
  image: ruby:2.7

  script:
    - gem install dpl
    - dpl --provider=heroku --app=$SERVER_HEROKU_APP --api-key=$HEROKU_SECRET_KEY --skip-cleanup=true

  dependencies:
    - export dependencies

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success