deploy-to-heroku:

  stage: deploy
  image: ruby:2.7

  script:
    - echo "$HEROKU_RUNTIME" > runtime.txt
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_SECRET_KEY --skip-cleanup=true

  dependencies:
    - unit-test-and-coverage

  only:
    refs:
      - master

    changes:
      - app
      - test
      - .gitlab-ci.yml
      - .gitlab/ci/**
      - poetry.lock