codestyle:
  <<: *quality
  script:
    - poetry run pylama server
  rules:
    - when: always


docstyle:
  <<: *quality
  script:
    - poetry run pydocstyle server
  allow_failure: true


black:
  <<: *quality
  script:
    - poetry run black -l 79 --check server
  rules:
    - when: always