unit tests:
  stage: testing
  image: python:3.8
  script:
    - pip install poetry && poetry install
    - poetry export -f requirements.txt > requirements.txt
    - poetry run pylama server
    - poetry run coverage run -m unittest discover -s test/unit -v
    - poetry run coverage report

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

  rules:
    - when: always