unit tests:
  <<: *test
  script:
    - poetry run coverage run -m unittest discover -s test/unit -v
    - poetry run coverage report

  dependencies:
    - codestyle
    - black

  rules:
    - when: on_success